#Restock
Restock = true
#Use fixed items
UseFixedItems = false
#Minable
Minable = false
#Add structure to Villages
Villages = true
#Fixed items; item or item,amount,pay_item,cost,uses
FixedItems = ["minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air"]
#Include Mods
IncludeMods = ["*"]
#Exclude Mods
ExcludeMods = ["draconicevolution", "avaritia", "botania"]
#Include Items
IncludeItems = ["*"]
#Exclude Items
ExcludeItems = ["minecraft:nether_star", "minecraft:beacon", "minecraft:bedrock", "minecraft:shulker_box", "minecraft:colorset*shulker_box", "minecraft:elytra", "minecraft:end_portal_frame", "minecraft:armorset*netherite", "minecraft:toolset*netherite", "minecraft:netherite_block", "minecraft:netherite_ingot", "minecraft:spawner", "minecraft:netherite_upgrade_smithing_template", "#minecraft:trim_templates", "-minecraft:coast_armor_trim_smithing_template", "vm:vending_machine"]
#Add Items
AddItems = [""]
#Include Creative Tab Groups
IncludeGroups = ["*"]
#Exclude Creative Tab Groups
ExcludeGroups = ["!", "op"]
#Change item rarity value for pricing
ItemRarity = ["minecraft:emerald_block=1", "minecraft:diamond_block=1", "minecraft:armorset*diamond=1", "minecraft:toolset*diamond=1", "minecraft:anvil=2", "minecraft:trident=3", "minecraft:bell=2", "minecraft:conduit=3", "minecraft:nautilus_shell=1", "eggset*peaceful=1", "eggset*monster=2", "minecraft:evoker_spawn_egg=3", "minecraft:warden_spawn_egg=3", "minecraft:netherite_scrap=2", "minecraft:ancient_debris=2", "minecraft:axolotl_bucket=1", "minecraft:echo_shard=3", "minecraft:lodestone=3", "minecraft:respawn_anchor=1", "minecraft:coast_armor_trim_smithing_template=3", "#minecraft:decorated_pot_sherds=1", "minecraft:arms_up_pottery_sherd=0"]
#Custom item pricing
ItemCost = [""]

[RarityData]
	#Common Item
	CommonItem = "minecraft:emerald"
	#Uncommon Item
	UncommonItem = "minecraft:emerald"
	#Rare Item
	RareItem = "minecraft:emerald"
	#Epic Item
	EpicItem = "minecraft:emerald"
	#Common Cost
	#Range: 0 ~ 128
	CommonCost = 1
	#Uncommon Cost
	#Range: 0 ~ 128
	UncommonCost = 16
	#Rare Cost
	#Range: 0 ~ 128
	RareCost = 32
	#Epic Cost
	#Range: 0 ~ 128
	EpicCost = 64
	#Common Uses
	#Range: 0 ~ 32
	CommonUses = 8
	#Uncommon Uses
	#Range: 0 ~ 32
	UncommonUses = 4
	#Rare Uses
	#Range: 0 ~ 32
	RareUses = 2
	#Epic Uses
	#Range: 0 ~ 32
	EpicUses = 1

